Removed the possibility to set timeperiods for simplicity of the plugin
eberhardt/moodle-block_coursefeedback pull request #17
Opened 2023-04-18 09:44 UTC by FelixDiLenarda

Fast ausschließlich code entfernt. 
Die Zeitperioden sind raus und müssen nicht mehr bei jedem Aufruf geparst werden.
Das Feedback muss jetzt manuell gestartet und gestoppt werden.
Die Funktionaliät den Block per oneklick in die Kurse auszurollen und zu entfernen kommt beim nächsten PR.

2023-06-01 09:57 UTC, eberhardt requested changes
Passe nochmal schnell das IF an, dann kann ich es annehmen. So ne Faulheit lasse ich dir nicht durchgehen. ^^

2023-06-01 09:57 UTC, eberhardt commented on block_coursefeedback.php
> -            }
Soll das ein leerer IF-Block bleiben?!?

2023-06-01 11:15 UTC, FelixDiLenarda commented on block_coursefeedback.php
> -            }
Hatte ich übersehen, das untere `else if` konnte auch raus, weil das durch `block_coursefeedback_questions_exist()`
abgedeckt ist ;)

2023-06-01 11:16 UTC, FelixDiLenarda commented on block_coursefeedback.php
> -            }
Hatte ich übersehen, das untere `else if` konnte auch raus, weil das durch `block_coursefeedback_questions_exist()`
abgedeckt ist ;)
[1afdb21](https://github.com/eberhardt/moodle-block_coursefeedback/pull/17/commits/1afdb21b21ba4e8360951fe27e20eb7ca45c160c)

2023-06-01 11:17 UTC, FelixDiLenarda commented on block_coursefeedback.php
> -            }
Hatte ich übersehen, das untere `else` konnte auch raus, weil das durch `block_coursefeedback_questions_exist()`
abgedeckt ist ;)
[1afdb21](https://github.com/eberhardt/moodle-block_coursefeedback/pull/17/commits/1afdb21b21ba4e8360951fe27e20eb7ca45c160c)

2023-06-01 11:51 UTC, eberhardt commented on block_coursefeedback.php
> -            }
Alright, dann ist ja schön.

2023-06-01 11:52 UTC, eberhardt requested changes

2023-06-01 11:52 UTC, eberhardt commented on block_coursefeedback.php
>          // Check if the feedback should be active in this course depending on the startdate (since_coursestart) setting.
Durch den neuen Commit grade tein gekommen. Mach mal das Kommentar verständlicher,

2023-06-05 08:32 UTC, FelixDiLenarda commented on block_coursefeedback.php
>          // Check if the feedback should be active in this course depending on the startdate (since_coursestart) setting.
[9eba9eb](https://github.com/eberhardt/moodle-block_coursefeedback/pull/17/commits/9eba9eb80d604e770a72c09e3bd9761a91fe058d)

2023-06-05 08:38 UTC, eberhardt commented on block_coursefeedback.php
>          // Check if the feedback should be active in this course depending on the startdate (since_coursestart) setting.
Passt.

2023-06-05 08:39 UTC, eberhardt approved these changes

2023-06-05 08:40 UTC, merged