Do not show empty essayanswers in the table
eberhardt/moodle-block_coursefeedback pull request #46
Opened 2024-02-01 13:10 UTC by FelixDiLenarda

Dieser PR verbessert die Darstellung der Freitextfragen-Antworten.
Leere Antworten werden nun gefiltert und nicht mehr in der Tabelle angezeigt.
Das Filtern passiert in den DB Abfragen selbst. Diese wurden dafür dementsprechend verändert.
Um den Lehrenden weiterhin die Info weiterzuleiten wieviele leere Antworten es gibt, wird dies über der Tabelle als kurze Info angezeigt.

2024-02-05 13:03 UTC, daniil-berg requested changes
Hier wären m.E. nur ein paar Änderungen wichtig. Einige Kommentare von mir sind Kleinigkeiten und wiederum andere beziehen sich nicht direkt per se auf diesen PR.

Grundsätzlich eine gute Idee und gut umgesetzt mit dem Filtern in der DB.

2024-02-05 13:03 UTC, daniil-berg commented on essayanswers.php
> +               AND textanswer <> ''";
An der Stelle ärgere ich mich über mich selber, dass ich das nicht schon beim PR, der die Tabelle hinzugefügt hat, bemerkt habe...

Das ist so ein typisches Problem mit `NULL`-baren String Feldern in einer DB Tabelle. In den allermeisten Fällen ist das eine schlechte Idee, weil es dann genau zu solchen `... IS NOT NULL AND ... <> ''` Abfragen kommt (im besten Fall) oder zu falschen Ergebnissen (im schlechtesten). Der Grund ist, dass _meistens_ ein Eintrag mit leerem String und einer mit `NULL` in dem Feld semantisch äquivalent sind.

In dieser konkreten Tabelle gibt es ja eigentlich nur die beiden Optionen 1. die Textantwort ist leer und 2. die Textantwort ist nicht leer oder noch präziser aus Anwenderlogik: Entweder der Teilnehmer hat die Frage übersprungen oder er hat eine Antwort gegeben.

In der Datenbank kann aber Variante 1 sowohl durch einen leeren String als auch durch `NULL` repräsentiert werden. Dadurch musst du beim Lesen immer aufpassen, beides zu checken und/oder beim Schreiben immer daran denken, nur genau eines von beiden zu wählen. Aus meiner Sicht ist es daher am einfachsten String Felder (in den meisten Fällen) `NOT NULL` zu definieren. So gibt es nur noch eine mögliche Repräsentation für "Teilnehmer hat die Frage nicht beantwortet", nämlich den leeren String in dem Eintrag.

Du kannst sogar explizit `DEFAULT ''` dazu setzen. So hast du im Prinzip das gleiche Verhalten wie mit `NULL`-barem Feld, aber ohne die Ambiguität.

Die umgekehrte Variante geht natürlich auch, also ein `NULL` zu erlauben und per `CONSTRAINT` den leeren String verbieten, aber das ist mir persönlich meistens umständlicher bzw. weniger klar in der Benutzung.

Ausnahmen gibt es sicherlich und falls ich komplett daneben liege und du hier einen guten Grund für die Unterscheidung zwischen `NULL` und `''` hast, ist meine Tirade hier natürlich hinfällig. Ansonsten würde ich empfehlen, dass demnächst noch zu ändern.

2024-02-05 13:03 UTC, daniil-berg commented on essayanswers.php
> +         WHERE course = :course
Das ist jetzt wieder eine Kleinigkeit, die nichts mit diesem PR an sich zu tun hat, aber mir fällt auf, dass inkonsequent in der Benennung der Tabellenfelder vorgegangen wurde. Also die anderen Foreign Keys haben jeweils das `id` Suffix, aber `course` nicht. Dass das analog zu der ursprünglichen [`block_coursefeedback_answers`](https://github.com/eberhardt/moodle-block_coursefeedback/blob/c36d8de431bf521c7d04e19edf7442dfb74d0c12/db/install.xml#L38-L55) Tabelle benannt ist, weiß ich, aber auch da ist es eben inkonsequent.

Hätte mir früher auffallen müssen, sorry. Würde trotzdem vorschlagen, dass demnächst zu ändern. Ist aber wie gesagt nur meine Pedanterie.

2024-02-05 13:03 UTC, daniil-berg commented on essayanswers.php
> +$anscount = $DB->count_records_sql($sql, $params);
Ich würde versuchen, immer die DML Funktionen zu wählen, die mir am wenigsten Freiheitsgrade bieten, da das die Fehleranfälligkeit reduziert. In dem Fall würde ich [`count_records_select`](https://moodledev.io/docs/apis/core/dml#count_records_select) verwenden.

```php
$select = "course = :course
       AND coursefeedbackid = :coursefeedbackid 
       AND questionid = :questionid 
       AND textanswer IS NOT NULL 
       AND textanswer <> ''";
$params = [
    'course' => $courseid,
    'coursefeedbackid' => $feedbackid,
    'questionid' => $questionid
];
$anscount = $DB->count_records_select('block_coursefeedback_textans', $select, $params);
```

2024-02-05 13:03 UTC, daniil-berg commented on lang/de/block_coursefeedback.php
> +$string['page_html_totalanscountinfo'] = 'Insgesamt {$a->anscount} nicht leere Antworten, Sie befinden sich auf Seie {$a->page} von {$a->totalpages}.';
Hier ist mir jetzt ein Tippfehler aufgefallen: In _"Sei**t**e"_ fehlt das "t". Auch würde ich hier zwei Sätze darauß machen, statt ein Komma zu verwenden. Aber das ist Geschmackssache.

2024-02-05 13:03 UTC, daniil-berg commented on renderer.php
> +        $emptyans = $totalcount-$anscount;
Leerzeichen um den Operator machen Ausdrücke besser lesbar.

2024-02-05 13:03 UTC, daniil-berg commented on renderer.php
> +            get_string("qtype_empty_essayans","block_coursefeedback", $emptyans));
Hier fehlt auch ein Leerzeichen nach dem ersten Komma.

2024-02-05 13:03 UTC, daniil-berg commented on renderer.php
> +        $answers = $DB->get_records_sql($sql, $params);
Gleiches Argument wie ober für `count_...`. Ich würde [`get_records_select`](https://moodledev.io/docs/apis/core/dml#get_records_select) verwenden und "halb-rohes" SQL nur dann, wenn es sich nicht vermeiden lässt.

```php
$select = "course = :courseid
       AND coursefeedbackid = :coursefeedbackid 
       AND questionid = :questionid 
       AND textanswer IS NOT NULL 
       AND textanswer <> ''";  // Hier wieder die doppelte Bedingung...
$params = [
    'courseid' => $courseid,
    'coursefeedbackid' => $feedbackid,
    'questionid' => $questionid,
];
$limitfrom = $perpage * $page;
$answers = $DB->get_records_select(
    'block_coursefeedback_textans',
    $select,
    $params,
    '',
    'id, textanswer',
    $limitfrom,
    $perpage,
);
```

2024-02-06 09:34 UTC, FelixDiLenarda commented on essayanswers.php
> +               AND textanswer <> ''";
Ja du hast vollkommen Recht! Beim Speichern von leeren Textantworten wird auch nie 'null' gespeichert sondern immer ''. D.h. eigentlich wäre die Abfrage 'IS NOT NULL ' überflüssig. Aber mit dem nullbaren Feld... sicher ist sicher.
Ich werde das in ZUkunft berücksichtigen und hab mir das auf meine Feature liste gesetzt.

2024-02-06 09:41 UTC, eberhardt commented on essayanswers.php
> +$anscount = $DB->count_records_sql($sql, $params);
Agreed.

2024-02-06 09:47 UTC, FelixDiLenarda commented on essayanswers.php
> +         WHERE course = :course
Verstehe den Punkt. Habs auch mal aufgeschrieben. In naher Zukunft sind aber erstmal andere Dinge wichtiger.

2024-02-06 11:15 UTC, FelixDiLenarda commented on essayanswers.php
> +         WHERE course = :course
Ja stimmt! Habe es geändert in: [4b6d4b3](https://github.com/eberhardt/moodle-block_coursefeedback/pull/46/commits/4b6d4b3e041114ab74d5bb64af9affcbc065c97b)

2024-02-06 11:16 UTC, FelixDiLenarda commented on essayanswers.php
> +$anscount = $DB->count_records_sql($sql, $params);
Ja stimmt, guter Punkt! Habe ich geändert in: Ja stimmt! Habe es geändert in: [4b6d4b3](https://github.com/eberhardt/moodle-block_coursefeedback/pull/46/commits/4b6d4b3e041114ab74d5bb64af9affcbc065c97b)

2024-02-06 11:17 UTC, FelixDiLenarda commented on renderer.php
> +        $answers = $DB->get_records_sql($sql, $params);
Ja stimmt, guter Punkt! Habe ich geändert in: [4b6d4b3](https://github.com/eberhardt/moodle-block_coursefeedback/pull/46/commits/4b6d4b3e041114ab74d5bb64af9affcbc065c97b)

2024-02-06 11:17 UTC, FelixDiLenarda commented on renderer.php
> +        $emptyans = $totalcount-$anscount;
Geändert in: [56bdd6e](https://github.com/eberhardt/moodle-block_coursefeedback/pull/46/commits/56bdd6e0a74c9cb66c2e48caabbf8d7589390b9e)

2024-02-06 11:17 UTC, FelixDiLenarda commented on renderer.php
> +            get_string("qtype_empty_essayans","block_coursefeedback", $emptyans));
Geändert in: [56bdd6e](https://github.com/eberhardt/moodle-block_coursefeedback/pull/46/commits/56bdd6e0a74c9cb66c2e48caabbf8d7589390b9e)

2024-02-06 11:23 UTC, daniil-berg approved these changes

2024-02-06 11:58 UTC, merged